version: '3'
services:
  app:
    image: user-service/user-service:latest
    environment:
      - SERVER_URL=mysql
    ports:
      - "8080:8080"

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"