version: '3'
services:
  app:
    build: .
    environment:
      - DB_HOSTNAME=postgres
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_USER=gdgtoledo
      - POSTGRES_DB=phones
    ports:
      - "8000:8000"

  postgres:
    image: postgres:9.5-alpine
    environment:
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_USER=gdgtoledo
      - POSTGRES_DB=phones
    ports:
      - "5432:5432"